### PR TITLE
Optimization for large mazes, issue #2.

### PR DESCRIPTION
**Pull request by paulafrederick**

### CODE REVIEW

**Comment by cyucelen** [comment]
Looks like flashing effect still exists

**Comment by paulafrederick** [comment]
I see some strange effect at the 2 last columns, is this?

**Comment by cyucelen** [comment]
Compared your implementation with the current, both flickering at the last lines.

**Comment by paulafrederick** [comment]
I got the problem, I'll investigate it.
Yes, my implementation just removes some global flickering.

**Comment by paulafrederick** [comment]
Guess i solved it now. Check if it's better now.

**Pull request merged**
